// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgmieuhpmqxnrnrjsszi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnbWlldWhwbXF4bnJucmpzc3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzg4MDgsImV4cCI6MjA2Njg1NDgwOH0.INWXpiOdH00VtbFBUCX-Jrp2bgKMcwJWilb8t6CKvc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});